(() => {
  const text = (zh, en, fr, de) => ({ zh, en, fr, de });
  const work = (id, file, title, caption, scene) => ({ id, file, title, caption, scene });

  window.MMV_ALBUM_DATA = [
    {
      id: "portraits",
      name: text("人物图鉴", "Portraits", "Portraits", "Porträts"),
      description: text(
        "六位成年女性，六种安静而明亮的生命姿态。",
        "Six adult women, each carrying a different kind of quiet radiance.",
        "Six femmes adultes, six façons calmes et lumineuses d’habiter le monde.",
        "Sechs erwachsene Frauen, sechs stille und leuchtende Arten, in der Welt zu sein.",
      ),
      medium: text("彩铅人物", "Coloured-pencil portrait", "Portrait au crayon de couleur", "Buntstiftporträt"),
      items: [
        work(
          "spring-window",
          "./assets/album/portraits/spring-window.webp",
          text("春窗", "Spring Window", "Fenêtre de printemps", "Frühlingsfenster"),
          text(
            "她二十二岁，坐在花影与晨光之间。风把枝叶的清香，也把春天带进屋里。",
            "At twenty-two, she sits between blossom shadows and morning light while the breeze carries spring indoors.",
            "À vingt-deux ans, elle s’assoit entre l’ombre des fleurs et la lumière du matin ; la brise fait entrer le printemps.",
            "Mit zweiundzwanzig sitzt sie zwischen Blütenschatten und Morgenlicht, während der Wind den Frühling ins Zimmer trägt.",
          ),
          text("春日 · 窗边", "Spring · by the window", "Printemps · près de la fenêtre", "Frühling · am Fenster"),
        ),
        work(
          "after-rain",
          "./assets/album/portraits/after-rain.webp",
          text("雨后", "After Rain", "Après la pluie", "Nach dem Regen"),
          text(
            "二十岁的她穿过雨后的大学花园，裙摆擦过湿润的草尖，神情轻快得像刚停的雨。",
            "The twenty-year-old crosses a university garden after rain, her long skirt brushing wet grass with an easy, bright step.",
            "À vingt ans, elle traverse le jardin universitaire après la pluie ; sa jupe frôle l’herbe mouillée d’un pas léger.",
            "Die Zwanzigjährige geht nach dem Regen durch den Universitätsgarten; ihr langer Rock streift leicht das nasse Gras.",
          ),
          text("初夏 · 花园", "Early summer · garden", "Début d’été · jardin", "Frühsommer · Garten"),
        ),
        work(
          "summer-lake",
          "./assets/album/portraits/summer-lake.webp",
          text("湖风", "Lake Breeze", "Brise du lac", "Seewind"),
          text(
            "二十四岁的她在湖边停下，青绿衣裙与水色相接。她没有摆好姿势，只是恰好被风看见。",
            "At twenty-four, she pauses beside the lake, teal fabric meeting the water—unposed, simply noticed by the wind.",
            "À vingt-quatre ans, elle s’arrête au bord du lac ; sa robe bleu-vert rejoint l’eau, sans pose, simplement saisie par le vent.",
            "Mit vierundzwanzig hält sie am See inne; ihr seegrünes Kleid trifft auf das Wasser—ungekünstelt, nur vom Wind bemerkt.",
          ),
          text("盛夏 · 湖畔", "High summer · lakeside", "Plein été · rive du lac", "Hochsommer · Seeufer"),
        ),
        work(
          "night-bookstore",
          "./assets/album/portraits/night-bookstore.webp",
          text("夜书店", "Night Bookshop", "Librairie de nuit", "Nachtbuchhandlung"),
          text(
            "二十六岁的她倚在书架旁翻到喜欢的一页。暖灯落在酒红衣襟上，夜色因此慢了下来。",
            "At twenty-six, she finds a favourite page beside the shelves; warm light settles on burgundy cloth and the night slows down.",
            "À vingt-six ans, elle retrouve une page aimée près des rayons ; la lumière chaude se pose sur le bordeaux et ralentit la nuit.",
            "Mit sechsundzwanzig findet sie am Regal eine Lieblingsseite; warmes Licht fällt auf Burgunderrot und lässt die Nacht langsamer werden.",
          ),
          text("夜晚 · 独立书店", "Evening · independent bookshop", "Soir · librairie indépendante", "Abend · unabhängige Buchhandlung"),
        ),
        work(
          "bicycle-morning",
          "./assets/album/portraits/bicycle-morning.webp",
          text("晨骑", "Morning Ride", "Échappée matinale", "Morgenfahrt"),
          text(
            "二十一岁的她骑过清晨的大学街区，车篮空着，路还很长，笑意已经先到了。",
            "The twenty-one-year-old rides through a quiet university quarter, basket empty, road long, smile already there.",
            "À vingt et un ans, elle traverse à vélo le quartier universitaire encore calme ; le panier est vide, le sourire déjà là.",
            "Die Einundzwanzigjährige fährt durch das stille Universitätsviertel; der Korb ist leer, der Weg lang, das Lächeln schon da.",
          ),
          text("清晨 · 城市街区", "Morning · city quarter", "Matin · quartier urbain", "Morgen · Stadtviertel"),
        ),
        work(
          "tea-house",
          "./assets/album/portraits/tea-house.webp",
          text("茶烟", "Tea Steam", "Vapeur de thé", "Teedampf"),
          text(
            "二十九岁的她在茶烟后抬眼，衣襟借了旧式线条，神情却属于此刻：从容、清醒，也温柔。",
            "At twenty-nine, she looks through rising tea steam; her dress borrows an old line, but her calm, lucid warmth belongs to now.",
            "À vingt-neuf ans, elle lève les yeux derrière la vapeur du thé ; sa tenue cite le passé, sa douceur lucide appartient au présent.",
            "Mit neunundzwanzig blickt sie durch den Teedampf; ihr Kleid zitiert alte Linien, ihre ruhige Klarheit gehört ganz der Gegenwart.",
          ),
          text("午后 · 现代茶室", "Afternoon · modern tea room", "Après-midi · salon de thé contemporain", "Nachmittag · modernes Teehaus"),
        ),
      ],
    },
    {
      id: "life",
      name: text("人间烟火", "Everyday Life", "Vie quotidienne", "Alltagsleben"),
      description: text(
        "热气、灯火和寻常日子里不经意的温柔。",
        "Steam, lamplight and the unplanned tenderness of ordinary days.",
        "La vapeur, les lumières et la tendresse imprévue des jours ordinaires.",
        "Dampf, Lampenlicht und die beiläufige Zärtlichkeit gewöhnlicher Tage.",
      ),
      medium: text("生活彩铅", "Coloured-pencil life study", "Scène de vie au crayon", "Alltagsstudie in Buntstift"),
      items: [
        work(
          "breakfast-stall",
          "./assets/album/life/breakfast-stall.webp",
          text("第一笼热气", "The First Steamer", "La première vapeur", "Der erste Dampf"),
          text(
            "天刚亮，竹笼先醒了。豆浆的甜香顺着街角，把赶路的人轻轻留住。",
            "At first light the bamboo steamer wakes before the street; sweet soy milk briefly holds hurried passers-by.",
            "À l’aube, le panier de bambou s’éveille avant la rue ; le parfum du lait de soja retient un instant les passants pressés.",
            "Im ersten Licht erwacht der Bambusdämpfer vor der Straße; der Duft süßer Sojamilch hält Eilige einen Augenblick fest.",
          ),
          text("清晨 · 街角早餐摊", "Dawn · corner breakfast stall", "Aube · étal du petit-déjeuner", "Morgengrauen · Frühstücksstand"),
        ),
        work(
          "evening-market",
          "./assets/album/life/evening-market.webp",
          text("晚市灯火", "Market Lights", "Lumières du marché", "Marktlichter"),
          text(
            "青菜还带着水珠，摊主把最后一盏灯点亮。夏夜从讨价还价声里慢慢展开。",
            "Greens still hold droplets as the final lamp comes on; a summer evening unfolds through friendly bargaining.",
            "Les légumes gardent leurs gouttes quand la dernière lampe s’allume ; la nuit d’été s’ouvre au rythme des marchandages.",
            "Auf dem Gemüse liegen noch Tropfen, als die letzte Lampe angeht; der Sommerabend entfaltet sich im freundlichen Feilschen.",
          ),
          text("夏夜 · 菜市场", "Summer night · produce market", "Nuit d’été · marché", "Sommernacht · Markt"),
        ),
        work(
          "dumpling-table",
          "./assets/album/life/dumpling-table.webp",
          text("围桌", "Around the Table", "Autour de la table", "Rund um den Tisch"),
          text(
            "面粉落在指尖，形状各不相同的饺子排成一圈。家人的话题，也在桌面上越包越满。",
            "Flour dusts every fingertip and uneven dumplings form a circle; family stories grow fuller around the table.",
            "La farine couvre les doigts et les raviolis inégaux forment un cercle ; les histoires de famille remplissent peu à peu la table.",
            "Mehl liegt auf den Fingerspitzen, ungleiche Teigtaschen bilden einen Kreis, und Familiengeschichten füllen den Tisch.",
          ),
          text("冬日 · 家中餐桌", "Winter · family table", "Hiver · table familiale", "Winter · Familientisch"),
        ),
        work(
          "rainy-store",
          "./assets/album/life/rainy-store.webp",
          text("雨夜小店", "Rainy Night Shop", "Échoppe sous la pluie", "Laden im Regen"),
          text(
            "檐下的灯把雨丝照成金色。陌生人收起伞，在一间小店门前共享片刻干燥。",
            "A shop lamp turns the rain gold; strangers close their umbrellas and share a brief patch of dryness.",
            "La lampe de l’échoppe dore la pluie ; des inconnus ferment leurs parapluies et partagent un court refuge au sec.",
            "Das Ladenlicht färbt den Regen golden; Fremde schließen ihre Schirme und teilen für einen Moment einen trockenen Ort.",
          ),
          text("雨夜 · 巷口", "Rainy night · lane corner", "Nuit pluvieuse · coin de ruelle", "Regennacht · Gassenecke"),
        ),
        work(
          "balcony-laundry",
          "./assets/album/life/balcony-laundry.webp",
          text("晒着午后", "An Afternoon on the Line", "Un après-midi suspendu", "Nachmittag auf der Leine"),
          text(
            "衬衫与床单兜住风，绿植在影子里轻晃。普通的午后，被晾得蓬松而明亮。",
            "Shirts and sheets catch the breeze while leaves sway below; an ordinary afternoon hangs light and soft.",
            "Chemises et draps retiennent la brise, les plantes oscillent en dessous ; l’après-midi ordinaire devient léger.",
            "Hemden und Laken fangen den Wind, Blätter wiegen sich darunter; ein gewöhnlicher Nachmittag hängt weich und hell.",
          ),
          text("午后 · 旧阳台", "Afternoon · old balcony", "Après-midi · vieux balcon", "Nachmittag · alter Balkon"),
        ),
        work(
          "alley-barber",
          "./assets/album/life/alley-barber.webp",
          text("黄昏理发店", "Barbershop at Dusk", "Coiffeur au crépuscule", "Friseurladen in der Dämmerung"),
          text(
            "木椅被岁月磨亮，收音机还在低声唱。黄昏沿着镜子，把老街多留了一会儿。",
            "Years have polished the wooden chair and the radio still murmurs; dusk lingers in the mirror of the old street.",
            "Les années ont poli le fauteuil de bois, la radio murmure encore ; le crépuscule s’attarde dans le miroir de la vieille rue.",
            "Die Jahre haben den Holzstuhl glatt poliert, das Radio murmelt; die Dämmerung verweilt im Spiegel der alten Straße.",
          ),
          text("黄昏 · 老街", "Dusk · old street", "Crépuscule · vieille rue", "Dämmerung · alte Straße"),
        ),
      ],
    },
    {
      id: "animals",
      name: text("动物图鉴", "Animals", "Animaux", "Tiere"),
      description: text(
        "那些不说话，却总能让世界安静下来的朋友。",
        "Quiet companions who make the world gentler without saying a word.",
        "Des compagnons silencieux qui adoucissent le monde sans un mot.",
        "Stille Gefährten, die die Welt ohne ein Wort sanfter machen.",
      ),
      medium: text("自然彩铅", "Coloured-pencil nature study", "Étude naturaliste au crayon", "Naturstudie in Buntstift"),
      items: [
        work(
          "orange-cat-window",
          "./assets/album/animals/orange-cat-window.webp",
          text("窗台观察员", "Window Watcher", "Guetteur de fenêtre", "Fensterwächter"),
          text(
            "雨停以后，橘猫把下巴搁在窗沿上。它看鸟，也看玻璃上最后一颗水珠慢慢落下。",
            "After the rain, an orange cat rests its chin on the sill, watching birds and the last drop slide down the glass.",
            "Après la pluie, un chat roux pose le menton sur l’appui, observant les oiseaux et la dernière goutte sur la vitre.",
            "Nach dem Regen legt eine orangefarbene Katze das Kinn aufs Fensterbrett und beobachtet Vögel und den letzten Tropfen am Glas.",
          ),
          text("雨后 · 窗台", "After rain · windowsill", "Après la pluie · appui de fenêtre", "Nach dem Regen · Fensterbrett"),
        ),
        work(
          "shiba-meadow",
          "./assets/album/animals/shiba-meadow.webp",
          text("风里有花", "Flowers in the Wind", "Des fleurs dans le vent", "Blumen im Wind"),
          text(
            "柴犬站在草坡最高处，耳朵迎着风。野花不必被摘下，也能陪它走很远。",
            "A shiba stands atop the meadow, ears to the wind; unpicked wildflowers are enough company for the long way home.",
            "Un shiba se tient au sommet de la prairie, les oreilles au vent ; les fleurs sauvages l’accompagnent sans être cueillies.",
            "Ein Shiba steht oben auf der Wiese, die Ohren im Wind; ungepflückte Wildblumen begleiten ihn weit nach Hause.",
          ),
          text("春野 · 草坡", "Spring field · meadow", "Prairie de printemps", "Frühlingsfeld · Wiese"),
        ),
        work(
          "red-panda-bamboo",
          "./assets/album/animals/red-panda-bamboo.webp",
          text("竹雾醒来", "Waking in Bamboo Mist", "Réveil dans la brume de bambou", "Erwachen im Bambusnebel"),
          text(
            "小熊猫从雾里的枝杈探出脸，尾巴绕成温暖的一圈。竹叶正接住清晨。",
            "A red panda peers through misty branches, tail curled into a warm ring while bamboo leaves catch the morning.",
            "Un panda roux apparaît entre les branches brumeuses, la queue en cercle chaud, tandis que les feuilles recueillent le matin.",
            "Ein Kleiner Panda schaut aus nebligen Zweigen, den Schwanz warm eingerollt, während Bambusblätter den Morgen auffangen.",
          ),
          text("晨雾 · 竹林", "Morning mist · bamboo grove", "Brume matinale · bambouseraie", "Morgennebel · Bambushain"),
        ),
        work(
          "cranes-wetland",
          "./assets/album/animals/cranes-wetland.webp",
          text("浅水来信", "A Letter in Shallow Water", "Lettre en eau peu profonde", "Brief im flachen Wasser"),
          text(
            "两只丹顶鹤在浅水间缓慢相遇，倒影先碰到一起，翅膀还保持着礼貌的距离。",
            "Two red-crowned cranes meet slowly in the shallows; their reflections touch before their wings do.",
            "Deux grues du Japon se rencontrent lentement dans l’eau basse ; leurs reflets se touchent avant leurs ailes.",
            "Zwei Mandschurenkraniche begegnen sich im flachen Wasser; ihre Spiegelbilder berühren sich vor den Flügeln.",
          ),
          text("清晨 · 湿地", "Morning · wetland", "Matin · zone humide", "Morgen · Feuchtgebiet"),
        ),
        work(
          "rabbit-garden",
          "./assets/album/animals/rabbit-garden.webp",
          text("香草丛里的耳朵", "Ears Among the Herbs", "Oreilles parmi les herbes", "Ohren zwischen Kräutern"),
          text(
            "白兔藏在薄荷与雏菊之间，以为自己只露出了一点点。花园知道全部，却没有揭穿。",
            "A white rabbit hides between mint and daisies, certain only its ears show; the garden knows better and keeps the secret.",
            "Un lapin blanc se cache entre menthe et pâquerettes, persuadé que seules ses oreilles dépassent ; le jardin garde le secret.",
            "Ein weißes Kaninchen versteckt sich zwischen Minze und Gänseblümchen; der Garten weiß mehr und bewahrt das Geheimnis.",
          ),
          text("午后 · 香草园", "Afternoon · herb garden", "Après-midi · jardin d’herbes", "Nachmittag · Kräutergarten"),
        ),
        work(
          "whale-dawn",
          "./assets/album/animals/whale-dawn.webp",
          text("海面第一声", "The Sea’s First Sound", "Le premier son de la mer", "Der erste Klang des Meeres"),
          text(
            "黎明把海面染得很淡，一道鲸尾从水中升起。远处的鸟群替它把消息带向天空。",
            "Dawn pales the sea as a whale’s tail rises; distant birds carry its quiet message into the sky.",
            "L’aube pâlit la mer lorsqu’une queue de baleine se lève ; les oiseaux lointains portent son message vers le ciel.",
            "Die Dämmerung macht das Meer blass, als eine Walflosse auftaucht; ferne Vögel tragen ihre stille Nachricht in den Himmel.",
          ),
          text("黎明 · 外海", "Dawn · open sea", "Aube · haute mer", "Morgengrauen · offene See"),
        ),
      ],
    },
    {
      id: "archives",
      name: text("史料文献", "Archives", "Archives", "Archive"),
      description: text(
        "关于保存、辨认与倾听过去的创作性档案意象；并非真实史料复刻。",
        "Artistic archive studies about preserving and listening to the past—not reproductions of historical records.",
        "Des évocations artistiques de l’archive et de l’écoute du passé, non des reproductions de documents historiques.",
        "Künstlerische Archivbilder über Bewahren und Zuhören—keine Reproduktionen historischer Quellen.",
      ),
      medium: text("档案意象 · 创作性重构", "Archive study · artistic reconstruction", "Étude d’archive · reconstitution artistique", "Archivstudie · künstlerische Rekonstruktion"),
      items: [
        work(
          "archive-morning",
          "./assets/album/archives/archive-morning.webp",
          text("档案室的早晨", "Morning in the Archive", "Matin aux archives", "Morgen im Archiv"),
          text(
            "棉手套、无酸纸盒与接触印样在晨光里依次醒来。保存过去，也是一种缓慢的照料。",
            "Cotton gloves, acid-free boxes and contact sheets wake in morning light; preserving the past is a patient form of care.",
            "Gants de coton, boîtes sans acide et planches-contact s’éveillent dans la lumière ; préserver le passé est un soin patient.",
            "Baumwollhandschuhe, säurefreie Schachteln und Kontaktbögen erwachen im Morgenlicht; Bewahren ist geduldige Fürsorge.",
          ),
          text("档案保存 · 艺术想象", "Archival care · artistic study", "Conservation · évocation artistique", "Archivpflege · künstlerische Studie"),
        ),
        work(
          "railway-keepsakes",
          "./assets/album/archives/railway-keepsakes.webp",
          text("站台留下的东西", "What the Platform Kept", "Ce que le quai a gardé", "Was der Bahnsteig bewahrte"),
          text(
            "旧车票、皮箱与停住的表被摆在一起。旅程已经结束，物件仍替人记着出发。",
            "An old ticket, suitcase and stopped watch sit together; the journey is over, but objects remember departure.",
            "Un vieux billet, une valise et une montre arrêtée demeurent ensemble ; le voyage est fini, les objets se souviennent du départ.",
            "Eine alte Fahrkarte, ein Koffer und eine stehengebliebene Uhr liegen beieinander; die Reise ist vorbei, die Dinge erinnern sich.",
          ),
          text("旅行旧物 · 艺术想象", "Travel keepsakes · artistic study", "Souvenirs de voyage · évocation", "Reiseandenken · künstlerische Studie"),
        ),
        work(
          "republican-letter",
          "./assets/album/archives/republican-letter.webp",
          text("未寄出的信", "The Unsent Letter", "La lettre jamais envoyée", "Der ungesendete Brief"),
          text(
            "旧式信笺停在未写完的一行，墨水已经干了。我们无法读清内容，只能听见纸张留下的犹豫。",
            "A period letter stops mid-line and the ink has dried; the words stay unreadable, but the paper still holds hesitation.",
            "Une lettre ancienne s’arrête au milieu d’une ligne ; les mots restent illisibles, mais le papier conserve l’hésitation.",
            "Ein alter Brief endet mitten in einer Zeile; die Worte bleiben unlesbar, doch das Papier bewahrt das Zögern.",
          ),
          text("旧式书信 · 艺术想象", "Period letter · artistic study", "Lettre ancienne · évocation", "Historischer Brief · künstlerische Studie"),
        ),
        work(
          "cyanotype-botany",
          "./assets/album/archives/cyanotype-botany.webp",
          text("蓝晒植物谱", "Cyanotype Herbarium", "Herbier cyanotype", "Cyanotypie-Herbarium"),
          text(
            "叶脉在普鲁士蓝里留下白色轮廓。植物从泥土离开后，又在光里获得第二次生命。",
            "Leaf veins leave pale silhouettes in Prussian blue; after leaving the soil, plants find a second life in light.",
            "Les nervures laissent leur silhouette claire dans le bleu de Prusse ; quittant la terre, les plantes renaissent dans la lumière.",
            "Blattadern hinterlassen helle Silhouetten in Preußischblau; fern der Erde finden Pflanzen im Licht ein zweites Leben.",
          ),
          text("植物档案 · 艺术想象", "Botanical archive · artistic study", "Archive botanique · évocation", "Botanisches Archiv · künstlerische Studie"),
        ),
        work(
          "county-gazetteer",
          "./assets/album/archives/county-gazetteer.webp",
          text("纸页里的山河", "A Landscape Between Pages", "Un paysage entre les pages", "Landschaft zwischen Seiten"),
          text(
            "线装书、木刻页与拓印工具围出一方小桌。不可辨认的墨迹，让山河只留下方向与重量。",
            "Thread-bound books, woodblock pages and rubbing tools gather on a desk; unreadable ink leaves only direction and weight.",
            "Livres cousus, pages gravées et outils d’estampage entourent la table ; l’encre illisible ne garde que direction et poids.",
            "Fadengebundene Bücher, Holzschnittseiten und Abreibwerkzeuge liegen beisammen; unlesbare Tinte bewahrt nur Richtung und Gewicht.",
          ),
          text("地方文献 · 艺术想象", "Local record · artistic study", "Document local · évocation", "Lokale Chronik · künstlerische Studie"),
        ),
        work(
          "oral-history-tape",
          "./assets/album/archives/oral-history-tape.webp",
          text("被保存的声音", "A Voice Preserved", "Une voix conservée", "Eine bewahrte Stimme"),
          text(
            "磁带安静地躺在录音机旁，标签上的字已模糊。真正留下来的，也许是停顿与呼吸。",
            "A cassette rests beside the recorder, its label blurred; what remains may be the pauses and breath between words.",
            "Une cassette repose près du magnétophone, son étiquette effacée ; restent peut-être les silences et les respirations.",
            "Eine Kassette liegt neben dem Aufnahmegerät, das Etikett verblasst; geblieben sind vielleicht Pausen und Atemzüge.",
          ),
          text("口述记忆 · 艺术想象", "Oral memory · artistic study", "Mémoire orale · évocation", "Mündliche Erinnerung · künstlerische Studie"),
        ),
      ],
    },
    {
      id: "illustrations",
      name: text("插画壁纸", "Illustrations", "Illustrations", "Illustrationen"),
      description: text(
        "适合把屏幕变成一扇窗的六幅轻幻想。",
        "Six gentle reveries made to turn a screen into a window.",
        "Six rêveries légères pour transformer l’écran en fenêtre.",
        "Sechs sanfte Tagträume, die den Bildschirm in ein Fenster verwandeln.",
      ),
      medium: text("彩铅幻想", "Coloured-pencil reverie", "Rêverie au crayon de couleur", "Buntstift-Tagtraum"),
      items: [
        work(
          "ginkgo-tide",
          "./assets/album/illustrations/ginkgo-tide.webp",
          text("银杏潮汐", "Ginkgo Tide", "Marée de ginkgo", "Ginkgoflut"),
          text(
            "金色叶片从枝头落下，又在纸面汇成潮水。秋天没有离开，只是换了一种流动方式。",
            "Golden leaves fall from branches and gather into a tide; autumn has not left, only changed how it moves.",
            "Les feuilles dorées tombent puis deviennent marée ; l’automne n’est pas parti, il a seulement changé de mouvement.",
            "Goldene Blätter fallen und sammeln sich zur Flut; der Herbst ist nicht gegangen, er bewegt sich nur anders.",
          ),
          text("秋日幻想", "Autumn reverie", "Rêverie d’automne", "Herbsttagtraum"),
        ),
        work(
          "cloud-whale",
          "./assets/album/illustrations/cloud-whale.webp",
          text("云鲸经过屋顶", "Cloud Whale over the Rooftops", "Baleine-nuage sur les toits", "Wolkenwal über den Dächern"),
          text(
            "清晨的云长成鲸的形状，从还没醒来的屋顶上方缓慢游过。没有人追赶，梦也就没有破。",
            "A morning cloud takes the shape of a whale and swims over sleeping roofs; no one chases it, so the dream stays whole.",
            "Un nuage du matin devient baleine et nage au-dessus des toits endormis ; personne ne le poursuit, le rêve reste intact.",
            "Eine Morgenwolke wird zum Wal und schwimmt über schlafende Dächer; niemand jagt ihr nach, also bleibt der Traum ganz.",
          ),
          text("清晨幻想", "Morning reverie", "Rêverie matinale", "Morgentraum"),
        ),
        work(
          "floral-constellation",
          "./assets/album/illustrations/floral-constellation.webp",
          text("野花星图", "Wildflower Constellation", "Constellation de fleurs", "Wildblumen-Sternbild"),
          text(
            "细线把野花与星点轻轻相连。仰望与俯身之间，原来只隔着一片夜色。",
            "Fine lines join wildflowers to stars; looking up and bending close are separated only by a little night.",
            "De fines lignes relient fleurs sauvages et étoiles ; lever les yeux et se pencher ne sont séparés que par un peu de nuit.",
            "Feine Linien verbinden Wildblumen und Sterne; zwischen Aufblicken und Hinabbeugen liegt nur ein wenig Nacht.",
          ),
          text("夜色幻想", "Night reverie", "Rêverie nocturne", "Nachttraum"),
        ),
        work(
          "summer-window",
          "./assets/album/illustrations/summer-window.webp",
          text("窗外正盛夏", "Summer Beyond the Window", "L’été derrière la fenêtre", "Sommer vor dem Fenster"),
          text(
            "风铃还没响，绿荫已经先涌进窗口。桌上的水杯，替房间收住一小块清凉。",
            "Before the wind chime sounds, green shade spills through the window; a glass of water holds a small piece of coolness.",
            "Avant même le carillon, l’ombre verte entre par la fenêtre ; un verre d’eau retient un morceau de fraîcheur.",
            "Noch bevor das Windspiel klingt, fließt grüner Schatten durchs Fenster; ein Wasserglas bewahrt ein Stück Kühle.",
          ),
          text("盛夏幻想", "High-summer reverie", "Rêverie d’été", "Hochsommertraum"),
        ),
        work(
          "koi-moon",
          "./assets/album/illustrations/koi-moon.webp",
          text("锦鲤衔月", "Koi Carrying the Moon", "Carpe portant la lune", "Koi trägt den Mond"),
          text(
            "月亮落进池水，锦鲤从光下游过，像把圆月短暂地衔在唇边。",
            "The moon falls into the pond and a koi passes beneath, seeming to carry the bright circle for a moment.",
            "La lune tombe dans l’étang ; une carpe passe sous sa lumière et semble porter un instant le cercle lumineux.",
            "Der Mond fällt in den Teich; ein Koi schwimmt darunter und scheint den hellen Kreis einen Moment zu tragen.",
          ),
          text("月夜幻想", "Moonlit reverie", "Rêverie au clair de lune", "Mondnachttraum"),
        ),
        work(
          "tea-garden",
          "./assets/album/illustrations/tea-garden.webp",
          text("雾中茶园", "Tea Garden in Mist", "Jardin de thé dans la brume", "Teegarten im Nebel"),
          text(
            "茶垄顺着山坡起伏，一间小屋在雾里亮着灯。远处很轻，归处很近。",
            "Tea rows follow the hillside while a small house glows in mist; the distance feels light and home feels near.",
            "Les rangées de thé suivent la pente, une petite maison brille dans la brume ; le lointain est léger, le refuge tout proche.",
            "Teereihen folgen dem Hang, ein kleines Haus leuchtet im Nebel; die Ferne wirkt leicht und das Zuhause nah.",
          ),
          text("山野幻想", "Hillside reverie", "Rêverie de montagne", "Bergtagtraum"),
        ),
      ],
    },
    {
      id: "comics",
      name: text("漫画图文", "Comics", "Bandes dessinées", "Comics"),
      description: text(
        "没有对白的小故事，让说明文字在画面之外慢慢接住它们。",
        "Wordless little stories, with their voices held gently outside the frame.",
        "De petites histoires sans dialogue, dont la voix se poursuit doucement hors cadre.",
        "Kleine Geschichten ohne Sprechblasen, deren Stimme behutsam außerhalb der Bilder weiterklingt.",
      ),
      medium: text("彩铅分镜", "Coloured-pencil comic", "Bande dessinée au crayon", "Buntstift-Comic"),
      items: [
        work(
          "cat-leaf",
          "./assets/album/comics/cat-leaf.webp",
          text("小猫带回一片秋天", "The Cat Brings Autumn Home", "Le chat rapporte l’automne", "Die Katze bringt den Herbst heim"),
          text(
            "它认真挑了一片最完整的落叶，一路叼回门口。礼物很轻，等待开门的心意却很重。",
            "It chooses the most perfect fallen leaf and carries it home; the gift is light, the wish behind it is not.",
            "Il choisit la feuille la plus intacte et la rapporte à la porte ; le cadeau est léger, l’intention ne l’est pas.",
            "Sie wählt das schönste gefallene Blatt und trägt es heim; das Geschenk ist leicht, die Absicht dahinter nicht.",
          ),
          text("四格 · 无对白", "Four panels · wordless", "Quatre cases · sans dialogue", "Vier Bilder · wortlos"),
        ),
        work(
          "train-window",
          "./assets/album/comics/train-window.webp",
          text("慢车窗外", "Outside the Slow Train", "Par la fenêtre du train lent", "Vor dem Fenster des langsamen Zuges"),
          text(
            "年轻的成年旅人靠着车窗，看田野从春绿走到秋黄。车没有变快，她也不再着急。",
            "A young adult traveller watches fields turn from spring green to autumn gold; the train stays slow, and she stops hurrying.",
            "Une jeune voyageuse adulte regarde les champs passer du vert au doré ; le train reste lent, elle cesse de se presser.",
            "Eine junge erwachsene Reisende sieht Felder von Frühlingsgrün zu Herbstgold wechseln; der Zug bleibt langsam, sie wird ruhig.",
          ),
          text("四格 · 无对白", "Four panels · wordless", "Quatre cases · sans dialogue", "Vier Bilder · wortlos"),
        ),
        work(
          "paper-boat",
          "./assets/album/comics/paper-boat.webp",
          text("纸船出发以后", "After the Paper Boat Leaves", "Après le départ du bateau de papier", "Nachdem das Papierboot ablegt"),
          text(
            "雨停后，一只纸船从街角的小水流出发。它绕过落叶，也绕过倒映在水里的天空。",
            "After rain, a paper boat departs along a street-corner stream, passing leaves and the sky reflected below.",
            "Après la pluie, un bateau de papier part dans le ruisseau du coin, longeant les feuilles et le ciel reflété.",
            "Nach dem Regen fährt ein Papierboot im Rinnsal an der Straßenecke los, vorbei an Blättern und dem gespiegelten Himmel.",
          ),
          text("四格 · 无对白", "Four panels · wordless", "Quatre cases · sans dialogue", "Vier Bilder · wortlos"),
        ),
        work(
          "rooftop-stars",
          "./assets/album/comics/rooftop-stars.webp",
          text("屋顶有一小片宇宙", "A Small Universe on the Roof", "Un petit univers sur le toit", "Ein kleines Universum auf dem Dach"),
          text(
            "两位成年朋友带着汽水爬上屋顶。城市的灯很亮，她们还是找到了几颗只属于今晚的星星。",
            "Two adult friends bring soda to the roof; despite the city lights, they find a few stars belonging only to tonight.",
            "Deux amis adultes montent sur le toit avec des sodas ; malgré les lumières de la ville, quelques étoiles n’appartiennent qu’à ce soir.",
            "Zwei erwachsene Freunde nehmen Limonade mit aufs Dach; trotz der Stadtlichter finden sie Sterne, die nur dieser Nacht gehören.",
          ),
          text("三格 · 无对白", "Three panels · wordless", "Trois cases · sans dialogue", "Drei Bilder · wortlos"),
        ),
        work(
          "pencil-garden",
          "./assets/picks/book-pencil-garden.webp",
          text("铅笔花园", "Pencil Garden", "Le jardin au crayon", "Der Bleistiftgarten"),
          text(
            "铅笔、书本和枝叶安静地躺在旧木桌上，像一段没有开始也不需要结束的午后。",
            "Pencils, books and leaves rest quietly on an old wooden table, like an afternoon that never started and never needs to end.",
            "Crayons, livres et feuillages reposent tranquillement sur une vieille table en bois, comme un après-midi sans début ni fin.",
            "Stifte, Bücher und Blätter ruhen still auf einem alten Holztisch — wie ein Nachmittag ohne Anfang und ohne Ende.",
          ),
          text("彩铅 · 静物", "Coloured pencil · still life", "Crayon de couleur · nature morte", "Buntstift · Stillleben"),
        ),
        work(
          "rain-light",
          "./assets/picks/film-pencil-rainlight.webp",
          text("雨光", "Rain Light", "Lumière de pluie", "Regenlicht"),
          text(
            "雨滴把窗外的灯晕成一片暖金色，镜头恰好停在这一帧。",
            "Raindrops soften the window lights into warm gold, and the lens pauses right on this frame.",
            "Les gouttes de pluie transforment les lumières de la fenêtre en un halo doré, et l'objectif s'arrête juste sur cette image.",
            "Regentropfen lassen die Fensterlichter warmgolden schimmern, und die Linse hält genau dieses Bild fest.",
          ),
          text("彩铅 · 光影", "Coloured pencil · light study", "Crayon de couleur · étude de lumière", "Buntstift · Lichtstudie"),
        ),
        work(
          "jasmine",
          "./assets/picks/music-pencil-jasmine.webp",
          text("茉莉", "Jasmine", "Jasmin", "Jasmin"),
          text(
            "一朵茉莉安静地开在旧乐谱旁边，像一首没有声音的歌。",
            "A jasmine blossom rests quietly beside an old music sheet, like a song without sound.",
            "Une fleur de jasmin repose tranquillement près d'une vieille partition, comme une chanson sans voix.",
            "Eine Jasminblüte ruht still neben alten Notenblättern, wie ein Lied ohne Klang.",
          ),
          text("彩铅 · 花卉", "Coloured pencil · floral", "Crayon de couleur · floral", "Buntstift · Blumen"),
        ),
      ],
    },
    {
      id: "landscapes",
      name: text("风光图景", "Landscapes", "Paysages", "Landschaften"),
      description: text(
        "从潮湿竹林到高山湖泊，收下天地不同的呼吸。",
        "From rain-soaked bamboo to alpine water, six ways the earth breathes.",
        "De la bambouseraie humide au lac alpin, six respirations de la terre.",
        "Vom regennassen Bambus bis zum Alpensee: sechs Atemzüge der Erde.",
      ),
      medium: text("风景彩铅", "Coloured-pencil landscape", "Paysage au crayon de couleur", "Buntstiftlandschaft"),
      items: [
        work(
          "rice-terraces",
          "./assets/album/landscapes/rice-terraces.webp",
          text("梯田醒在云下", "Terraces Waking under Cloud", "Rizières éveillées sous les nuages", "Terrassen erwachen unter Wolken"),
          text(
            "云南梯田在晨雾里一层层亮起，水面收住天光，也收住山村刚开始的一天。",
            "Yunnan rice terraces brighten layer by layer in morning mist, holding sky light and the village’s beginning day.",
            "Les rizières en terrasses du Yunnan s’éclairent dans la brume, retenant le ciel et le jour naissant du village.",
            "Die Reisterrassen Yunnans leuchten im Morgennebel Schicht für Schicht und bewahren Himmel und Tagesbeginn des Dorfes.",
          ),
          text("云南 · 晨雾", "Yunnan · morning mist", "Yunnan · brume matinale", "Yunnan · Morgennebel"),
        ),
        work(
          "sea-cliff",
          "./assets/album/landscapes/sea-cliff.webp",
          text("海崖晚风", "Evening Wind on the Cliffs", "Vent du soir sur la falaise", "Abendwind an der Klippe"),
          text(
            "草坡在海风里向同一个方向低伏，落日把崖壁染暖。远处的浪，替沉默一遍遍回答。",
            "Cliff grass bends with the sea wind as sunset warms the rock; distant waves answer silence again and again.",
            "L’herbe de la falaise s’incline dans le vent marin, le couchant réchauffe la roche ; les vagues répondent au silence.",
            "Das Gras an der Klippe beugt sich im Seewind, die Abendsonne wärmt den Fels; ferne Wellen antworten der Stille.",
          ),
          text("海岸 · 日落", "Coast · sunset", "Côte · coucher de soleil", "Küste · Sonnenuntergang"),
        ),
        work(
          "snow-village",
          "./assets/album/landscapes/snow-village.webp",
          text("蓝调雪村", "Blue-Hour Snow Village", "Village enneigé à l’heure bleue", "Schneedorf zur blauen Stunde"),
          text(
            "雪把道路与屋顶的棱角放软，第一盏窗灯在蓝色黄昏里亮起，像一句很小的欢迎。",
            "Snow softens roads and rooftops; the first window glows in blue dusk like a very small welcome.",
            "La neige adoucit routes et toits ; la première fenêtre s’allume dans le soir bleu comme un discret mot de bienvenue.",
            "Schnee macht Straßen und Dächer weich; im blauen Abend leuchtet das erste Fenster wie ein leiser Willkommensgruß.",
          ),
          text("冬日 · 蓝调时刻", "Winter · blue hour", "Hiver · heure bleue", "Winter · blaue Stunde"),
        ),
        work(
          "bamboo-rain",
          "./assets/album/landscapes/bamboo-rain.webp",
          text("竹林听雨", "Listening to Rain in Bamboo", "Écouter la pluie dans les bambous", "Regen im Bambus hören"),
          text(
            "江南细雨落进竹林，远近都是不同深浅的绿。石阶不催人，只把脚步带得更慢。",
            "Fine Jiangnan rain enters the bamboo grove in many greens; stone steps do not hurry anyone, only slow the walk.",
            "La pluie fine du Jiangnan traverse la bambouseraie en mille verts ; les marches de pierre ralentissent simplement le pas.",
            "Feiner Jiangnan-Regen fällt in den Bambushain voller Grüntöne; Steinstufen drängen nicht, sie machen den Schritt nur langsamer.",
          ),
          text("江南 · 细雨", "Jiangnan · fine rain", "Jiangnan · pluie fine", "Jiangnan · feiner Regen"),
        ),
        work(
          "desert-poplar",
          "./assets/album/landscapes/desert-poplar.webp",
          text("胡杨燃起的傍晚", "Evening among Desert Poplars", "Soir parmi les peupliers du désert", "Abend bei den Wüstenpappeln"),
          text(
            "胡杨在沙地上举起金色枝叶，夕阳把树影拉得很长。荒凉与丰盛，在这里同时成立。",
            "Desert poplars lift golden leaves over sand as sunset lengthens their shadows; barrenness and abundance coexist.",
            "Les peupliers du désert lèvent leurs feuilles d’or sur le sable ; au couchant, dépouillement et abondance coexistent.",
            "Wüstenpappeln tragen goldene Blätter über dem Sand, ihre Schatten werden lang; Kargheit und Fülle bestehen zugleich.",
          ),
          text("西北 · 日落", "Northwest China · sunset", "Nord-ouest chinois · coucher de soleil", "Nordwestchina · Sonnenuntergang"),
        ),
        work(
          "alpine-lake",
          "./assets/album/landscapes/alpine-lake.webp",
          text("高山湖的清晨", "Morning at the Alpine Lake", "Matin au lac alpin", "Morgen am Alpensee"),
          text(
            "风还没有抵达，雪峰完整地留在湖面上。清晨把世界对折，安静得看不出哪一边是真实。",
            "Before the wind arrives, snow peaks remain whole on the lake; morning folds the world until neither side seems more real.",
            "Avant le vent, les sommets enneigés restent entiers sur le lac ; le matin plie le monde, les deux côtés deviennent également réels.",
            "Bevor der Wind kommt, liegen die Schneegipfel ungebrochen im See; der Morgen faltet die Welt, beide Seiten wirken gleich wirklich.",
          ),
          text("高山 · 晨光", "Alpine · morning light", "Haute montagne · lumière matinale", "Hochgebirge · Morgenlicht"),
        ),
      ],
    },
  ];
})();
